version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2025.11
    steps:
      - checkout
      - run: echo "Building complete"
  test-node:
    docker:
      - image: cimg/node:25.1.0
    steps:
      - run: echo "Testing complete"
  test-node-24:
    docker:
      - image: cimg/node:24.2.0
    steps:
      - run: echo "Testing complete"
  test-node-23:
    docker:
      - image: cimg/node:23.11.1
    steps:
      - run: echo "Testing complete"
  deploy:
      docker:
        - image: cimg/base:2025.11
      steps:
        - run: echo "DEPLOYING" # Make sure all tests pass first!

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test-node
      - test-node-24
      - test-node-23
      - deploy
